repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: trailing-whitespace
        exclude: ^tools/patches/
      - id: end-of-file-fixer
        exclude: ^tools/patches/
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
      - id: no-commit-to-branch
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        name: Black
        args: [--line-length=99]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: [--profile=black]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Flake8
        args: [
            "--ignore=E203,E704,W503,W504,E501",
            "--max-line-length=99"
        ]
        additional_dependencies: [flake8-bugbear]
